### ISSUE TITLE
Critical error in a packaged Windows exe

### ISSUE THREAD

**Issue by goodhyun** [barinali/electron-packager-languages#11]
Well, I spent almost a week trying to find the root cause of this symptom, but it was the 0.3.0 of this module. 

If your app has either 
`<input type="file" />`
or Google login popup screen,
then your app silently crashes with the devtool disconnected. 

We had to rollback to 0.1.0, which doesn't seem to touch Windows part.

**Comment by barinali** [comment]
@goodhyun, thanks for filing such an issue. I'll check on the mentioned scenario in my first convenient time.

**Comment by barinali** [comment]
I have tested both scenarios you shared. However, I could not reproduce the bug in the `master` branch. Therefore, I will close the comment. If you think it persists and due to `electron-packager-languages`, please let me know, with a detailed log if possible.

**Comment by barinali** [comment]
#60 should have resolved the issue mentioned here.
